config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'aboutmes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/aboutmes_controller.rb
class AboutmesController < ApplicationController
  before_action :set_aboutme, only: [:show, :edit, :update, :destroy]

  # GET /aboutmes
  # GET /aboutmes.json
  def index
    
  end

  # GET /aboutmes/1
  # GET /aboutmes/1.json
  def show
  end

  # GET /aboutmes/new
  def new
    @aboutme = Aboutme.new
  end

  # GET /aboutmes/1/edit
  def edit
  end

  # POST /aboutmes
  # POST /aboutmes.json
  def create
    @aboutme = Aboutme.new(aboutme_params)

    respond_to do |format|
      if @aboutme.save
        format.html { redirect_to @aboutme, notice: 'Aboutme was successfully created.' }
        format.json { render :show, status: :created, location: @aboutme }
      else
        format.html { render :new }
        format.json { render json: @aboutme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aboutmes/1
  # PATCH/PUT /aboutmes/1.json
  def update
    respond_to do |format|
      if @aboutme.update(aboutme_params)
        format.html { redirect_to @aboutme, notice: 'Aboutme was successfully updated.' }
        format.json { render :show, status: :ok, location: @aboutme }
      else
        format.html { render :edit }
        format.json { render json: @aboutme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aboutmes/1
  # DELETE /aboutmes/1.json
  def destroy
    @aboutme.destroy
    respond_to do |format|
      format.html { redirect_to aboutmes_url, notice: 'Aboutme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aboutme
      @aboutme = Aboutme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aboutme_params
      params.fetch(:aboutme, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/aboutmes_helper.rb
module AboutmesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aboutmes/_form.html.erb
<%= form_for(aboutme) do |f| %>
  <% if aboutme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aboutme.errors.count, "error") %> prohibited this aboutme from being saved:</h2>

      <ul>
      <% aboutme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aboutmes/edit.html.erb
<h1>Editing Aboutme</h1>

<%= render 'form', aboutme: @aboutme %>

<%= link_to 'Show', @aboutme %> |
<%= link_to 'Back', aboutmes_path %>

app/views/aboutmes/index.html.erb
<p id="notice"><%= notice %></p>

<div>
<h2>Здравствуйте.</h2>
  <h3>Меня зовут Кирилл и я ненавижу писать резюме.</h3>
  <br/>
  <img src='https://health.mail.ru/pic/news/2015/10/07/ea/cb/eacbf20ec44e1cc9d3e2e9edff4b0ec3.jpg'/>
  <br/>
</div>

<div>
  <ul>
    <li><a href= "bio.html">Биография</a>
    <li><a href= "skills.html">Навыки</a>
  </ul>
</div>


<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  
</table>

<br>

app/views/aboutmes/new.html.erb
<h1>New Aboutme</h1>

<%= render 'form', aboutme: @aboutme %>

<%= link_to 'Back', aboutmes_path %>

app/views/aboutmes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_aboutme_path(@aboutme) %> |
<%= link_to 'Back', aboutmes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Представление</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>